version: 0.2

phases:
  install:
    runtime-versions:
       dotnet: 2.2
  build:
    commands:
      - dotnet publish src/Server/Host/PBWeb.Server/PBWeb.Server.csproj --configuration Release --output "../../../../Output/Server"
      - dotnet publish src/Novitas.Pension.Web/Novitas.Pension.Web.csproj --configuration Release --output "../../Output/Application"
      
      #- dotnet build src/Server/Host/PBWeb.Server/PBWeb.Server.csproj /nologo /p:PublishProfile=Release /p:PackageLocation="..\..\..\..\output" /p:OutDir="..\..\..\..\out\server" /p:DeployOnBuild=true /p:PackageAsSingleFile=true /p:configuration="Release"
      #- dotnet build src/Novitas.Pension.Web/Novitas.Pension.Web.csproj /nologo /p:PublishProfile=Release /p:PackageLocation="..\..\..\..\output" /p:OutDir="..\..\..\..\out\application" /p:DeployOnBuild=true /p:PackageAsSingleFile=true /p:configuration="Release"
artifacts:
  files:
    - Output/**/*
  name: PbWeb-$(date +%Y-%m-%d)

